import dotenv from 'dotenv'
require("node:dns/promises").setServers(["1.1.1.1", "8.8.8.8"]);

dotenv.config()

import mongoose from 'mongoose'
import Hotel from '../models/Hotel'

const hotels = [
  // ── RAJASTHAN (Magical Rajasthan) ──
  {
    name: 'Hotel Pearl Palace',
    city: 'Jaipur', state: 'Rajasthan', region: 'North India',
    address: 'Hathroi Fort Road, Ajmer Road, Jaipur',
    nearestLandmark: 'MI Road',
    howToReach: '2 km from Jaipur Railway Station, 12 km from Jaipur Airport',
    rating: 4.3, reviews: 1820,
    pricePerNight: { economy: 1800, premium: 2200 },
    amenities: ['WiFi', 'Restaurant', 'Travel Desk', 'Laundry', 'Airport Pickup', 'Rooftop'],
    images: ['/images/hotels/Pearl Palace Heritage Hotel in Jaipur (Premium).jpg'],
    description: 'A charming heritage hotel with colourful rooftop and great city views. Walking distance from the Pink City markets.',
    coordinates: { lat: 26.9124, lng: 75.7873 },
    type: 'budget', tags: ['Budget', 'Rooftop', 'Central'],
    builtYear: 1995,
  },
  {
    name: 'Govind Hotel',
    city: 'Jaisalmer', state: 'Rajasthan', region: 'North India',
    address: 'Opposite Jaisalmer Railway Station, Rajasthan',
    nearestLandmark: 'Jaisalmer Fort',
    howToReach: 'Walking distance from railway station',
    rating: 4.1, reviews: 890,
    pricePerNight: { economy: 1500, premium: 2000 },
    amenities: ['WiFi', 'Restaurant', 'Desert Safari Booking', 'Free Pickup'],
    images: ['/images/hotels/Gobindgarh Luxury Hotel & Resort Jaisalmer (Premium).jpg'],
    description: 'A convenient budget hotel directly opposite Jaisalmer Railway Station with fort views and desert safari bookings.',
    coordinates: { lat: 26.9157, lng: 70.9083 },
    type: 'budget', tags: ['Budget', 'Fort View', 'Desert'],
    builtYear: 1990,
  },
  {
    name: 'Umaid Bhawan Palace',
    city: 'Jodhpur', state: 'Rajasthan', region: 'North India',
    address: 'Circuit House Road, Jodhpur',
    nearestLandmark: 'Mehrangarh Fort',
    howToReach: '5 km from Jodhpur Airport',
    rating: 4.7, reviews: 2340,
    pricePerNight: { economy: 20000, premium: 35000 },
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Museum', 'Bar'],
    images: ['/images/hotels/Umaid Bhawan Palace Jodhpur (Premium).jpg'],
    description: 'One of the world\'s finest heritage hotels, part of which is still the royal family\'s residence. Museum, spa and magnificent architecture.',
    coordinates: { lat: 26.2839, lng: 73.0665 },
    type: 'luxury', tags: ['Palace', 'Heritage', 'Luxury'],
    builtYear: 1943,
  },

  // ── RAJASTHAN (Romantic Udaipur) ──
  {
    name: 'Hotel Pushkar Palace',
    city: 'Pushkar', state: 'Rajasthan', region: 'North India',
    address: 'Choti Basti, Pushkar',
    nearestLandmark: 'Pushkar Lake',
    howToReach: '15 km from Ajmer Railway Station',
    rating: 4.1, reviews: 760,
    pricePerNight: { economy: 2000, premium: 2800 },
    amenities: ['WiFi', 'Restaurant', 'Pool', 'Garden'],
    images: ['/images/hotels/Hotel-pushkar-palace (Premium).jpg'],
    description: 'A serene hotel overlooking the sacred Pushkar Lake with a pool and garden. Perfect for spiritual travellers.',
    coordinates: { lat: 26.4896, lng: 74.5511 },
    type: 'mid-range', tags: ['Lake View', 'Spiritual', 'Pool'],
    builtYear: 1998,
  },

  // ── KASHMIR ──
  {
    name: 'Hotel Pine Spring',
    city: 'Gulmarg', state: 'Jammu & Kashmir', region: 'North India',
    address: 'Gulmarg Road, Gulmarg',
    nearestLandmark: 'Gulmarg Gondola',
    howToReach: '60 km from Srinagar',
    rating: 4.0, reviews: 620,
    pricePerNight: { economy: 2500, premium: 3500 },
    amenities: ['WiFi', 'Restaurant', 'Heater', 'Mountain View'],
    images: ['/images/hotels/Hotel Pine Spring Gulmarg (Economy).jpg'],
    description: 'A cosy budget hotel in the meadow of Gulmarg with stunning mountain views and easy access to the gondola.',
    coordinates: { lat: 34.0480, lng: 74.3805 },
    type: 'budget', tags: ['Mountain View', 'Budget', 'Snow'],
    builtYear: 2005,
  },
  {
    name: 'The Lalit Grand Palace',
    city: 'Srinagar', state: 'Jammu & Kashmir', region: 'North India',
    address: 'Gupkar Road, Srinagar',
    nearestLandmark: 'Dal Lake',
    howToReach: '18 km from Srinagar Airport',
    rating: 4.6, reviews: 1560,
    pricePerNight: { economy: 18000, premium: 25000 },
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Gardens', 'Bar'],
    images: ['/images/hotels/Lalit Grand Palace Srinagar (Premium).jpg'],
    description: 'A heritage palace built in 1910 on the shores of Dal Lake offering Himalayan panoramas and royal Kashmiri hospitality.',
    coordinates: { lat: 34.0837, lng: 74.7973 },
    type: 'luxury', tags: ['Heritage', 'Lake View', 'Luxury'],
    builtYear: 1910,
  },
  {
    name: 'Khyber Himalayan Resort & Spa',
    city: 'Gulmarg', state: 'Jammu & Kashmir', region: 'North India',
    address: 'Gulmarg, Near Gondola Phase 1',
    nearestLandmark: 'Gondola Phase 1',
    howToReach: '65 km from Srinagar',
    rating: 4.7, reviews: 1120,
    pricePerNight: { economy: 20000, premium: 30000 },
    amenities: ['Heated Pool', 'Spa', 'Restaurant', 'WiFi', 'Ski Access'],
    images: ['/images/hotels/Khyber Himalayan Resort & Spa Gulmarg (Premium).jpg'],
    description: 'Gulmarg\'s finest luxury resort with heated pool and direct ski slope access. Chalets and luxury rooms with snow-capped views.',
    coordinates: { lat: 34.0480, lng: 74.3805 },
    type: 'luxury', tags: ['Ski Resort', 'Luxury', 'Spa'],
    builtYear: 2012,
  },

  // ── MAHARASHTRA ──
  {
    name: 'Hotel Panchavati',
    city: 'Aurangabad', state: 'Maharashtra', region: 'West India',
    address: 'Station Road, Aurangabad, Maharashtra',
    nearestLandmark: 'Bibi Ka Maqbara',
    howToReach: '2 km from Aurangabad Railway Station, 10 km from Airport',
    rating: 4.1, reviews: 980,
    pricePerNight: { economy: 1800, premium: 2300 },
    amenities: ['WiFi', 'Restaurant', 'Parking', 'Travel Desk'],
    images: ['/images/hotels/Hotel-panchavati Aurangabad (Economy).jpg'],
    description: 'A well-located budget hotel near Aurangabad railway station, ideal base for visiting Ajanta and Ellora caves.',
    coordinates: { lat: 19.8762, lng: 75.3433 },
    type: 'budget', tags: ['Budget', 'Central', 'Caves Base'],
    builtYear: 2002,
  },
  {
    name: 'Hotel Sai Suraj Palace',
    city: 'Shirdi', state: 'Maharashtra', region: 'West India',
    address: 'Pimpalwadi Road, Shirdi',
    nearestLandmark: 'Sai Baba Temple',
    howToReach: '3 km from Sainagar Shirdi Railway Station',
    rating: 4.0, reviews: 1240,
    pricePerNight: { economy: 1500, premium: 2200 },
    amenities: ['WiFi', 'Restaurant', 'Temple Shuttle', 'Parking'],
    images: ['/images/hotels/Hotel Sai Suraj Park Shirdi (Primium).jpg'],
    description: 'A comfortable hotel near the sacred Sai Baba Temple with temple shuttle service for convenient darshan visits.',
    coordinates: { lat: 19.7647, lng: 74.4777 },
    type: 'budget', tags: ['Spiritual', 'Budget', 'Temple Nearby'],
    builtYear: 2008,
  },
  {
    name: 'Vivanta Aurangabad',
    city: 'Aurangabad', state: 'Maharashtra', region: 'West India',
    address: 'Jalna Road, Aurangabad',
    nearestLandmark: 'Prozone Mall',
    howToReach: '10 km from Aurangabad Airport',
    rating: 4.5, reviews: 1560,
    pricePerNight: { economy: 10000, premium: 15000 },
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Gym', 'Business Center'],
    images: ['/images/hotels/Vivanta Aurangabad (Premium).jpg'],
    description: 'A premium Taj Hotels property in Aurangabad offering modern luxury near the historic cave complexes.',
    coordinates: { lat: 19.8762, lng: 75.3980 },
    type: 'luxury', tags: ['Luxury', 'Business', 'Pool'],
    builtYear: 2007,
  },

  // ── HIMACHAL PRADESH ──
  {
    name: 'Hotel Shingar',
    city: 'Shimla', state: 'Himachal Pradesh', region: 'North India',
    address: 'The Mall Road, Shimla',
    nearestLandmark: 'Christ Church',
    howToReach: '2 km from Shimla Bus Stand',
    rating: 4.0, reviews: 870,
    pricePerNight: { economy: 2000, premium: 3000 },
    amenities: ['WiFi', 'Restaurant', 'Heater', 'Room Service'],
    images: ['/images/hotels/Hotel Shingar Shimla (Economy).jpg'],
    description: 'A budget hotel on the iconic Mall Road in Shimla with easy access to all major attractions.',
    coordinates: { lat: 31.1048, lng: 77.1734 },
    type: 'budget', tags: ['Mall Road', 'Budget', 'Central'],
    builtYear: 1995,
  },
  {
    name: 'Hotel New Adarsh',
    city: 'Manali', state: 'Himachal Pradesh', region: 'North India',
    address: 'Near Mall Road, Manali',
    nearestLandmark: 'Hadimba Temple',
    howToReach: '1 km from Manali Bus Stand',
    rating: 4.1, reviews: 1020,
    pricePerNight: { economy: 1800, premium: 2800 },
    amenities: ['WiFi', 'Restaurant', 'Parking', 'Room Service', 'Mountain View'],
    images: ['/images/hotels/Hotel Adarsh Annexe Manali (Economy).jpg'],
    description: 'A cosy budget hotel near Hadimba Temple in Manali with valley views and proximity to the Mall Road.',
    coordinates: { lat: 32.2396, lng: 77.1887 },
    type: 'budget', tags: ['Mountain View', 'Budget', 'Valley'],
    builtYear: 2001,
  },
  {
    name: 'The Oberoi Cecil',
    city: 'Shimla', state: 'Himachal Pradesh', region: 'North India',
    address: 'Chaura Maidan, Shimla',
    nearestLandmark: 'Mall Road',
    howToReach: '3 km from Shimla Railway Station',
    rating: 4.7, reviews: 1890,
    pricePerNight: { economy: 18000, premium: 25000 },
    amenities: ['Spa', 'Heated Pool', 'Restaurant', 'WiFi', 'Bar', 'Gym'],
    images: ['/images/hotels/The Oberoi Shilma (Primium).jpg'],
    description: 'A legendary colonial-era hotel built in 1884, offering timeless luxury and panoramic views of the Himalayas from Shimla.',
    coordinates: { lat: 31.1048, lng: 77.1734 },
    type: 'luxury', tags: ['Heritage', 'Colonial', 'Luxury'],
    builtYear: 1884,
  },

  // ── UTTARAKHAND (Kumaon) ──
  {
    name: 'Hotel Himalaya',
    city: 'Nainital', state: 'Uttarakhand', region: 'North India',
    address: 'The Mall Road, Nainital',
    nearestLandmark: 'Naini Lake',
    howToReach: '35 km from Kathgodam Railway Station',
    rating: 4.1, reviews: 1140,
    pricePerNight: { economy: 2000, premium: 3000 },
    amenities: ['WiFi', 'Restaurant', 'Parking', 'Lake View'],
    images: ['/images/hotels/Hotel Himalaya Nainital (Economy).jpg'],
    description: 'A well-situated budget hotel on Mall Road with beautiful Naini Lake views and walking access to all Nainital attractions.',
    coordinates: { lat: 29.3803, lng: 79.4636 },
    type: 'budget', tags: ['Lake View', 'Budget', 'Mall Road'],
    builtYear: 1990,
  },
  {
    name: 'Chevron Rosemount',
    city: 'Ranikhet', state: 'Uttarakhand', region: 'North India',
    address: 'Mall Road, Ranikhet',
    nearestLandmark: 'Jhula Devi Temple',
    howToReach: '75 km from Kathgodam Railway Station',
    rating: 4.2, reviews: 640,
    pricePerNight: { economy: 2500, premium: 3200 },
    amenities: ['WiFi', 'Restaurant', 'Garden', 'Bonfire', 'Mountain View'],
    images: ['/images/hotels/Hotel Chevron Ranikhet (Economy).jpg'],
    description: 'A heritage hotel built in 1900 with lush gardens and Himalayan views, offering a peaceful retreat in Ranikhet.',
    coordinates: { lat: 29.6437, lng: 79.4322 },
    type: 'mid-range', tags: ['Heritage', 'Garden', 'Peaceful'],
    builtYear: 1900,
  },
  {
    name: 'The Naini Retreat',
    city: 'Nainital', state: 'Uttarakhand', region: 'North India',
    address: 'Ayarpatta Slopes, Nainital',
    nearestLandmark: 'Naina Devi Temple',
    howToReach: '35 km from Kathgodam Railway Station',
    rating: 4.5, reviews: 980,
    pricePerNight: { economy: 10000, premium: 15000 },
    amenities: ['Spa', 'Restaurant', 'WiFi', 'Garden', 'Lake View'],
    images: ['/images/hotels/The Naini Retreat Nainital (Premium).jpg'],
    description: 'A heritage luxury retreat built in 1880 on the slopes above Nainital, offering stunning lake views and spa treatments.',
    coordinates: { lat: 29.3803, lng: 79.4636 },
    type: 'luxury', tags: ['Heritage', 'Spa', 'Lake View'],
    builtYear: 1880,
  },
  {
    name: 'Aahana Resort',
    city: 'Jim Corbett', state: 'Uttarakhand', region: 'North India',
    address: 'Ramnagar, Uttarakhand',
    nearestLandmark: 'Jim Corbett National Park',
    howToReach: '12 km from Ramnagar Railway Station',
    rating: 4.7, reviews: 1320,
    pricePerNight: { economy: 15000, premium: 25000 },
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Nature Walks', 'Safari Booking'],
    images: ['/images/hotels/Ahana Resort Corbett (Economy).jpg'],
    description: 'A luxury wildlife resort at Jim Corbett with jungle-facing villas, nature walks, and safari packages.',
    coordinates: { lat: 29.5300, lng: 78.7747 },
    type: 'luxury', tags: ['Wildlife', 'Safari', 'Jungle'],
    builtYear: 2013,
  },

  // ── UTTARAKHAND (Divine) ──
  {
    name: 'Hotel Alpana',
    city: 'Haridwar', state: 'Uttarakhand', region: 'North India',
    address: 'Upper Road, Haridwar',
    nearestLandmark: 'Har Ki Pauri',
    howToReach: '1 km from Haridwar Railway Station',
    rating: 4.0, reviews: 760,
    pricePerNight: { economy: 1200, premium: 2000 },
    amenities: ['WiFi', 'Restaurant', 'Lift', 'Room Service'],
    images: ['/images/hotels/Hotel Alpana (Haridwar) (Economy).jpg'],
    description: 'A budget hotel just 1 km from Haridwar Railway Station and walking distance from the sacred Har Ki Pauri ghat.',
    coordinates: { lat: 29.9457, lng: 78.1642 },
    type: 'budget', tags: ['Spiritual', 'Budget', 'Central'],
    builtYear: 2000,
  },
  {
    name: 'JW Marriott Mussoorie Walnut Grove',
    city: 'Mussoorie', state: 'Uttarakhand', region: 'North India',
    address: 'Kempty Falls Road, Mussoorie',
    nearestLandmark: 'Kempty Falls',
    howToReach: '35 km from Dehradun Railway Station',
    rating: 4.7, reviews: 2100,
    pricePerNight: { economy: 18000, premium: 25000 },
    amenities: ['Spa', 'Pool', 'Multiple Restaurants', 'WiFi', 'Kids Zone', 'Bar'],
    images: ['/images/hotels/JW Marriott Mussoorie Walnut Grove Resort (Premium).jpg'],
    description: 'A stunning luxury resort near Kempty Falls with valley views, multiple dining options and a world-class spa.',
    coordinates: { lat: 30.4598, lng: 78.0644 },
    type: 'luxury', tags: ['Luxury', 'Valley View', 'Spa'],
    builtYear: 2014,
  },

  // ── GUJARAT ──
  {
    name: 'Hotel Accolade',
    city: 'Ahmedabad', state: 'Gujarat', region: 'West India',
    address: 'Ashram Road, Ahmedabad, Gujarat',
    nearestLandmark: 'Sabarmati Ashram',
    howToReach: '6 km from Ahmedabad Railway Station, 12 km from Airport',
    rating: 4.0, reviews: 870,
    pricePerNight: { economy: 1500, premium: 2200 },
    amenities: ['WiFi', 'Restaurant', 'Parking', 'Room Service'],
    images: ['/images/hotels/Hotel Accolade (Ahmedabad) (Economy).jpg'],
    description: 'A clean budget hotel on Ashram Road, conveniently located near Sabarmati Ashram and Ahmedabad city centre.',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    type: 'budget', tags: ['Budget', 'Central', 'Business'],
    builtYear: 2005,
  },
  {
    name: 'The Fern Gir Forest Resort',
    city: 'Gir', state: 'Gujarat', region: 'West India',
    address: 'Sasan Gir, Gujarat',
    nearestLandmark: 'Gir National Park',
    howToReach: '65 km from Junagadh Railway Station',
    rating: 4.5, reviews: 1080,
    pricePerNight: { economy: 10000, premium: 15000 },
    amenities: ['Pool', 'Restaurant', 'WiFi', 'Safari Booking', 'Nature Walks'],
    images: ['/images/hotels/The Fern Gir Forest Resort (Premium).jpg'],
    description: 'An eco-luxury resort adjacent to the Gir National Park — the only home of the Asiatic Lion. Safari bookings arranged.',
    coordinates: { lat: 21.1237, lng: 70.8240 },
    type: 'luxury', tags: ['Wildlife', 'Safari', 'Eco Resort'],
    builtYear: 2012,
  },

  // ── ODISHA ──
  {
    name: 'Hotel Sea Palace',
    city: 'Puri', state: 'Odisha', region: 'East India',
    address: 'Swargadwar Beach Road, Puri, Odisha',
    nearestLandmark: 'Jagannath Temple',
    howToReach: '3 km from Puri Railway Station',
    rating: 4.1, reviews: 890,
    pricePerNight: { economy: 1500, premium: 2200 },
    amenities: ['WiFi', 'Restaurant', 'Beach View', 'Room Service'],
    images: ['/images/hotels/Hotel Sea Palace (Puri) (Economy).jpg'],
    description: 'A budget hotel with sea views near the Jagannath Temple. Perfect for pilgrims and beach lovers on a budget.',
    coordinates: { lat: 19.8135, lng: 85.8312 },
    type: 'budget', tags: ['Beach View', 'Spiritual', 'Budget'],
    builtYear: 2003,
  },
  {
    name: 'Mayfair Waves',
    city: 'Puri', state: 'Odisha', region: 'East India',
    address: 'Chakratirtha Road, Puri',
    nearestLandmark: 'Puri Beach',
    howToReach: '4 km from Puri Railway Station',
    rating: 4.6, reviews: 1340,
    pricePerNight: { economy: 12000, premium: 18000 },
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Beach Access', 'Gym'],
    images: ['/images/hotels/Mayfair Waves (Puri) (Premium).jpg'],
    description: 'A luxury beachfront resort with direct beach access, outdoor pool, and excellent Odia cuisine restaurant.',
    coordinates: { lat: 19.7867, lng: 85.8302 },
    type: 'luxury', tags: ['Beach', 'Luxury', 'Pool'],
    builtYear: 2015,
  },

  // ── ONE DAY TRIPS — MUMBAI (Lonavala) ──
  {
    name: 'Hotel Rama Krishna',
    city: 'Lonavala', state: 'Maharashtra', region: 'West India',
    address: 'Near Lonavala Market & Railway Station',
    nearestLandmark: 'Lonavala Railway Station',
    howToReach: 'Walking distance from station',
    rating: 3.9, reviews: 540,
    pricePerNight: { economy: 1200, premium: 2000 },
    amenities: ['AC Rooms', 'Parking', '24hr Reception', 'Room Service'],
    images: ['/images/hotels/Hotel Rama Krishna Mumbai (Economy).jpg'],
    description: 'A budget hotel near Lonavala station, ideal for a quick overnight stay on a day trip from Mumbai.',
    coordinates: { lat: 18.7481, lng: 73.4072 },
    type: 'budget', tags: ['Budget', 'Day Trip Base', 'Central'],
    builtYear: 2000,
  },
  {
    name: 'Fariyas Resort Lonavala',
    city: 'Lonavala', state: 'Maharashtra', region: 'West India',
    address: 'Hill View Area, Lonavala',
    nearestLandmark: 'Lonavala Lake',
    howToReach: '4 km from Lonavala Railway Station',
    rating: 4.4, reviews: 1560,
    pricePerNight: { economy: 6000, premium: 9000 },
    amenities: ['Pool', 'Spa', 'Restaurant', 'WiFi', 'Indoor Games', 'Bar'],
    images: ['/images/hotels/Fariyas Resort Lonavala (Premium).jpg'],
    description: 'A scenic luxury resort in Lonavala hills with swimming pool, spa and indoor games. Perfect for family vacations.',
    coordinates: { lat: 18.7481, lng: 73.4072 },
    type: 'luxury', tags: ['Pool', 'Luxury', 'Hill View'],
    builtYear: 2003,
  },

  // ── ONE DAY TRIPS — CHENNAI (Mahabalipuram) ──
  {
    name: 'Hotel Mamalla Heritage',
    city: 'Mahabalipuram', state: 'Tamil Nadu', region: 'South India',
    address: 'Near Shore Temple, Mahabalipuram',
    nearestLandmark: 'Shore Temple',
    howToReach: '60 km from Chennai, cab available',
    rating: 4.2, reviews: 980,
    pricePerNight: { economy: 1500, premium: 2500 },
    amenities: ['Pool', 'Restaurant', 'WiFi', 'AC Rooms'],
    images: ['/images/hotels/Hotel Mamalla Heritage Mahabalipuram (Premium).jpg'],
    description: 'A heritage hotel walking distance from the Shore Temple with a good pool and restaurant. Value for money.',
    coordinates: { lat: 12.6269, lng: 80.1927 },
    type: 'mid-range', tags: ['Heritage', 'Temple View', 'Pool'],
    builtYear: 1995,
  },
  {
    name: 'Radisson Blu Resort Temple Bay',
    city: 'Mahabalipuram', state: 'Tamil Nadu', region: 'South India',
    address: 'Kovalam Road, Mahabalipuram',
    nearestLandmark: 'Shore Temple',
    howToReach: '58 km from Chennai Airport',
    rating: 4.6, reviews: 2100,
    pricePerNight: { economy: 8000, premium: 12000 },
    amenities: ['Private Beach', 'Pool', 'Spa', 'Restaurant', 'WiFi', 'Watersports'],
    images: ['/images/hotels/Radisson Blu Resort Temple Bay Mamallapuram (Premium).jpg'],
    description: 'One of the best beachfront luxury resorts near Chennai with private beach access and world-class amenities.',
    coordinates: { lat: 12.6269, lng: 80.1927 },
    type: 'luxury', tags: ['Beach', 'Luxury', 'Spa'],
    builtYear: 2004,
  },

  // ── ONE DAY TRIPS — VISAKHAPATNAM (Araku Valley) ──
  {
    name: 'Haritha Valley Resort',
    city: 'Araku Valley', state: 'Andhra Pradesh', region: 'South India',
    address: 'Araku Valley, Visakhapatnam District',
    nearestLandmark: 'Araku Coffee Museum',
    howToReach: '115 km from Visakhapatnam by Vistadome train',
    rating: 3.9, reviews: 430,
    pricePerNight: { economy: 1200, premium: 2000 },
    amenities: ['Restaurant', 'Parking', 'Garden', 'WiFi'],
    images: ['/images/hotels/Haritha Valley Resort Araku Valley (Economy).jpg'],
    description: 'A government tourism hotel in Araku Valley — safe, reliable and surrounded by coffee plantations and scenic valley views.',
    coordinates: { lat: 18.3273, lng: 82.8757 },
    type: 'budget', tags: ['Budget', 'Nature', 'Government Hotel'],
    builtYear: 2000,
  },
  {
    name: 'Casa Holiday Resorts',
    city: 'Araku Valley', state: 'Andhra Pradesh', region: 'South India',
    address: 'Araku Valley, Andhra Pradesh',
    nearestLandmark: 'Borra Caves',
    howToReach: '120 km from Visakhapatnam',
    rating: 4.3, reviews: 620,
    pricePerNight: { economy: 4000, premium: 6000 },
    amenities: ['Restaurant', 'Garden', 'Valley View', 'WiFi', 'Bonfire'],
    images: ['/images/hotels/Casa Holiday Resorts Araku (Premium).jpg'],
    description: 'A peaceful resort with stunning valley views near Borra Caves. Perfect for nature lovers seeking a quiet mountain escape.',
    coordinates: { lat: 18.3273, lng: 82.8757 },
    type: 'mid-range', tags: ['Valley View', 'Nature', 'Peaceful'],
    builtYear: 2010,
  },

  // ── ONE DAY TRIPS — GANGTOK (Sikkim) ──
  {
    name: 'Hotel Tashi Delek',
    city: 'Gangtok', state: 'Sikkim', region: 'East India',
    address: 'MG Marg Nearby, Gangtok',
    nearestLandmark: 'MG Marg',
    howToReach: '124 km from Bagdogra Airport',
    rating: 4.0, reviews: 780,
    pricePerNight: { economy: 1500, premium: 2500 },
    amenities: ['Restaurant', 'WiFi', 'Room Service', 'Mountain View'],
    images: ['/images/hotels/Hotel Tashi Delek Keylong (Economy).jpg'],
    description: 'A centrally located budget hotel near MG Marg in Gangtok with mountain views and easy access to all attractions.',
    coordinates: { lat: 27.3389, lng: 88.6065 },
    type: 'budget', tags: ['Budget', 'Central', 'Mountain View'],
    builtYear: 2005,
  },
  {
    name: 'Mayfair Spa Resort & Casino',
    city: 'Gangtok', state: 'Sikkim', region: 'East India',
    address: 'Gangtok, Sikkim',
    nearestLandmark: 'MG Marg',
    howToReach: '120 km from Bagdogra Airport',
    rating: 4.6, reviews: 1450,
    pricePerNight: { economy: 10000, premium: 15000 },
    amenities: ['Casino', 'Spa', 'Restaurant', 'WiFi', 'Luxury Cottages', 'Bar'],
    images: ['/images/hotels/Mayfair Spa Resort & Casino Gangtok (Premium).jpg'],
    description: 'The top luxury property in Sikkim featuring a casino, spa and luxury cottages with Himalayan panoramas.',
    coordinates: { lat: 27.3389, lng: 88.6065 },
    type: 'luxury', tags: ['Luxury', 'Casino', 'Spa'],
    builtYear: 2008,
  },

  // ── ONE DAY TRIPS — DELHI (Agra) ──
  {
    name: 'Hotel Sidhartha',
    city: 'Agra', state: 'Uttar Pradesh', region: 'North India',
    address: 'Near Taj Mahal, Agra',
    nearestLandmark: 'Taj Mahal',
    howToReach: 'Walking distance from Taj Mahal, 5 km from Agra Cantt Station',
    rating: 3.9, reviews: 1120,
    pricePerNight: { economy: 1200, premium: 2000 },
    amenities: ['AC Rooms', 'Restaurant', 'Parking', 'WiFi'],
    images: ['/images/hotels/Hotel Sidhartha Agra (Economy).jpg'],
    description: 'A budget hotel walking distance from the Taj Mahal — great for an early sunrise visit without the commute.',
    coordinates: { lat: 27.1767, lng: 78.0081 },
    type: 'budget', tags: ['Taj Mahal Nearby', 'Budget', 'Central'],
    builtYear: 2001,
  },
  {
    name: 'Hotel Taj Resorts',
    city: 'Agra', state: 'Uttar Pradesh', region: 'North India',
    address: 'Near Taj Mahal, Agra',
    nearestLandmark: 'Taj Mahal',
    howToReach: '5 km from Agra Cantt Railway Station',
    rating: 4.2, reviews: 1340,
    pricePerNight: { economy: 2000, premium: 3500 },
    amenities: ['Rooftop View', 'Pool', 'Restaurant', 'WiFi', 'Bar'],
    images: ['/images/hotels/Hotel Taj Resorts Agra ( Premium).jpg'],
    description: 'A mid-range hotel with a rooftop terrace offering Taj Mahal views. Pool and good restaurant on premises.',
    coordinates: { lat: 27.1767, lng: 78.0081 },
    type: 'mid-range', tags: ['Taj View', 'Rooftop', 'Pool'],
    builtYear: 2003,
  },

  // ── ONE DAY TRIPS — GOA ──
  {
    name: 'Taj Fort Aguada Resort & Spa',
    city: 'North Goa', state: 'Goa', region: 'West India',
    address: 'Sinquerim, Bardez, North Goa',
    nearestLandmark: 'Fort Aguada',
    howToReach: '40 km from Goa Airport',
    rating: 4.8, reviews: 3200,
    pricePerNight: { economy: 12000, premium: 20000 },
    amenities: ['Private Beach', 'Pool', 'Spa', 'Multiple Restaurants', 'WiFi', 'Watersports'],
    images: ['/images/hotels/Taj Fort Aguada Resort & Spa Goa (Premium).jpg'],
    description: 'An iconic beachfront Taj property next to the historic Fort Aguada with private beach, luxury pools and fine dining.',
    coordinates: { lat: 15.4920, lng: 73.7730 },
    type: 'luxury', tags: ['Beach', 'Iconic', 'Luxury'],
    builtYear: 1974,
  },
]

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI!)
    console.log('MongoDB connected')

    await Hotel.deleteMany({})
    console.log('Cleared existing hotels')

    await Hotel.insertMany(hotels)
    console.log(`✅ Seeded ${hotels.length} hotels with real data and images!`)

    process.exit(0)
  } catch (err) {
    console.error('Seed failed:', err)
    process.exit(1)
  }
}

seed()